<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Announcement extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Announcement_model');
    } 

    /*
     * Listing of announcements
     */
    function index()
    {
        $params['limit'] = RECORDS_PER_PAGE; 
        $params['offset'] = ($this->input->get('per_page')) ? $this->input->get('per_page') : 0;
        
        $config = $this->config->item('pagination');
        $config['base_url'] = site_url('announcement/index?');
        $config['total_rows'] = $this->Announcement_model->get_all_announcements_count();
        $this->pagination->initialize($config);

        $data['announcements'] = $this->Announcement_model->get_all_announcements($params);
        
        $data['_view'] = 'announcement/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new announcement
     */
    function add()
    {   
        $this->load->library('form_validation');

		$this->form_validation->set_rules('announceTitle','AnnounceTitle','required|max_length[50]');
		$this->form_validation->set_rules('announceFile','AnnounceFile','required|max_length[150]');
		$this->form_validation->set_rules('announceDate','AnnounceDate','required|max_length[50]');
		$this->form_validation->set_rules('dateUploaded','DateUploaded','required');
		$this->form_validation->set_rules('dateModified','DateModified','required');
		$this->form_validation->set_rules('dateExpiry','DateExpiry','required');
		$this->form_validation->set_rules('announceDetail','AnnounceDetail','required|max_length[150]');
		
		if($this->form_validation->run())     
        {   
            $params = array(
				'userID' => $this->input->post('userID'),
				'announceTitle' => $this->input->post('announceTitle'),
				'announceFile' => $this->input->post('announceFile'),
				'announceDate' => $this->input->post('announceDate'),
				'dateUploaded' => $this->input->post('dateUploaded'),
				'dateModified' => $this->input->post('dateModified'),
				'dateExpiry' => $this->input->post('dateExpiry'),
				'announceDetail' => $this->input->post('announceDetail'),
            );
            
            $announcement_id = $this->Announcement_model->add_announcement($params);
            redirect('announcement/index');
        }
        else
        {
			$this->load->model('User_model');
			$data['all_users'] = $this->User_model->get_all_users();
            
            $data['_view'] = 'announcement/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a announcement
     */
    function edit($announceID)
    {   
        // check if the announcement exists before trying to edit it
        $data['announcement'] = $this->Announcement_model->get_announcement($announceID);
        
        if(isset($data['announcement']['announceID']))
        {
            $this->load->library('form_validation');

			$this->form_validation->set_rules('announceTitle','AnnounceTitle','required|max_length[50]');
			$this->form_validation->set_rules('announceFile','AnnounceFile','required|max_length[150]');
			$this->form_validation->set_rules('announceDate','AnnounceDate','required|max_length[50]');
			$this->form_validation->set_rules('dateUploaded','DateUploaded','required');
			$this->form_validation->set_rules('dateModified','DateModified','required');
			$this->form_validation->set_rules('dateExpiry','DateExpiry','required');
			$this->form_validation->set_rules('announceDetail','AnnounceDetail','required|max_length[150]');
		
			if($this->form_validation->run())     
            {   
                $params = array(
					'userID' => $this->input->post('userID'),
					'announceTitle' => $this->input->post('announceTitle'),
					'announceFile' => $this->input->post('announceFile'),
					'announceDate' => $this->input->post('announceDate'),
					'dateUploaded' => $this->input->post('dateUploaded'),
					'dateModified' => $this->input->post('dateModified'),
					'dateExpiry' => $this->input->post('dateExpiry'),
					'announceDetail' => $this->input->post('announceDetail'),
                );

                $this->Announcement_model->update_announcement($announceID,$params);            
                redirect('announcement/index');
            }
            else
            {
				$this->load->model('User_model');
				$data['all_users'] = $this->User_model->get_all_users();

                $data['_view'] = 'announcement/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The announcement you are trying to edit does not exist.');
    } 

    /*
     * Deleting announcement
     */
    function remove($announceID)
    {
        $announcement = $this->Announcement_model->get_announcement($announceID);

        // check if the announcement exists before trying to delete it
        if(isset($announcement['announceID']))
        {
            $this->Announcement_model->delete_announcement($announceID);
            redirect('announcement/index');
        }
        else
            show_error('The announcement you are trying to delete does not exist.');
    }
    
}
