<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Class extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Class_model');
    } 

    /*
     * Listing of classes
     */
    function index()
    {
        $data['classes'] = $this->Class_model->get_all_classes();
        
        $data['_view'] = 'class/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new class
     */
    function add()
    {   
        $this->load->library('form_validation');

		$this->form_validation->set_rules('subjectID','SubjectID','required|integer');
		$this->form_validation->set_rules('facultyID','FacultyID','required|integer');
		$this->form_validation->set_rules('timeSlotID','TimeSlotID','required|integer');
		$this->form_validation->set_rules('venueID','VenueID','required|integer');
		$this->form_validation->set_rules('academicYear','AcademicYear','required|max_length[4]');
		$this->form_validation->set_rules('semester','Semester','required|max_length[10]');
		
		if($this->form_validation->run())     
        {   
            $params = array(
				'subjectID' => $this->input->post('subjectID'),
				'facultyID' => $this->input->post('facultyID'),
				'timeSlotID' => $this->input->post('timeSlotID'),
				'venueID' => $this->input->post('venueID'),
				'academicYear' => $this->input->post('academicYear'),
				'semester' => $this->input->post('semester'),
            );
            
            $class_id = $this->Class_model->add_class($params);
            redirect('class/index');
        }
        else
        {
			$this->load->model('Subject_model');
			$data['all_subjects'] = $this->Subject_model->get_all_subjects();

			$this->load->model('Faculty_model');
			$data['all_faculty'] = $this->Faculty_model->get_all_faculty();

			$this->load->model('Timeslot_model');
			$data['all_timeslots'] = $this->Timeslot_model->get_all_timeslots();

			$this->load->model('Venue_model');
			$data['all_venues'] = $this->Venue_model->get_all_venues();
            
            $data['_view'] = 'class/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a class
     */
    function edit($classID)
    {   
        // check if the class exists before trying to edit it
        $data['class'] = $this->Class_model->get_class($classID);
        
        if(isset($data['class']['classID']))
        {
            $this->load->library('form_validation');

			$this->form_validation->set_rules('subjectID','SubjectID','required|integer');
			$this->form_validation->set_rules('facultyID','FacultyID','required|integer');
			$this->form_validation->set_rules('timeSlotID','TimeSlotID','required|integer');
			$this->form_validation->set_rules('venueID','VenueID','required|integer');
			$this->form_validation->set_rules('academicYear','AcademicYear','required|max_length[4]');
			$this->form_validation->set_rules('semester','Semester','required|max_length[10]');
		
			if($this->form_validation->run())     
            {   
                $params = array(
					'subjectID' => $this->input->post('subjectID'),
					'facultyID' => $this->input->post('facultyID'),
					'timeSlotID' => $this->input->post('timeSlotID'),
					'venueID' => $this->input->post('venueID'),
					'academicYear' => $this->input->post('academicYear'),
					'semester' => $this->input->post('semester'),
                );

                $this->Class_model->update_class($classID,$params);            
                redirect('class/index');
            }
            else
            {
				$this->load->model('Subject_model');
				$data['all_subjects'] = $this->Subject_model->get_all_subjects();

				$this->load->model('Faculty_model');
				$data['all_faculty'] = $this->Faculty_model->get_all_faculty();

				$this->load->model('Timeslot_model');
				$data['all_timeslots'] = $this->Timeslot_model->get_all_timeslots();

				$this->load->model('Venue_model');
				$data['all_venues'] = $this->Venue_model->get_all_venues();

                $data['_view'] = 'class/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The class you are trying to edit does not exist.');
    } 

    /*
     * Deleting class
     */
    function remove($classID)
    {
        $class = $this->Class_model->get_class($classID);

        // check if the class exists before trying to delete it
        if(isset($class['classID']))
        {
            $this->Class_model->delete_class($classID);
            redirect('class/index');
        }
        else
            show_error('The class you are trying to delete does not exist.');
    }
    
}
