<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Faculty extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Faculty_model');
    } 

    /*
     * Listing of faculty
     */
    function index()
    {
        $data['faculty'] = $this->Faculty_model->get_all_faculty();
        
        $data['_view'] = 'faculty/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new faculty
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'userID' => $this->input->post('userID'),
				'facultyType' => $this->input->post('facultyType'),
				'minUnits' => $this->input->post('minUnits'),
				'maxUnits' => $this->input->post('maxUnits'),
				'dateAdded' => $this->input->post('dateAdded'),
				'dateModified' => $this->input->post('dateModified'),
            );
            
            $faculty_id = $this->Faculty_model->add_faculty($params);
            redirect('faculty/index');
        }
        else
        {            
            $data['_view'] = 'faculty/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a faculty
     */
    function edit($facultyID)
    {   
        // check if the faculty exists before trying to edit it
        $data['faculty'] = $this->Faculty_model->get_faculty($facultyID);
        
        if(isset($data['faculty']['facultyID']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'userID' => $this->input->post('userID'),
					'facultyType' => $this->input->post('facultyType'),
					'minUnits' => $this->input->post('minUnits'),
					'maxUnits' => $this->input->post('maxUnits'),
					'dateAdded' => $this->input->post('dateAdded'),
					'dateModified' => $this->input->post('dateModified'),
                );

                $this->Faculty_model->update_faculty($facultyID,$params);            
                redirect('faculty/index');
            }
            else
            {
                $data['_view'] = 'faculty/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The faculty you are trying to edit does not exist.');
    } 

    /*
     * Deleting faculty
     */
    function remove($facultyID)
    {
        $faculty = $this->Faculty_model->get_faculty($facultyID);

        // check if the faculty exists before trying to delete it
        if(isset($faculty['facultyID']))
        {
            $this->Faculty_model->delete_faculty($facultyID);
            redirect('faculty/index');
        }
        else
            show_error('The faculty you are trying to delete does not exist.');
    }
    
}
