<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Venue extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Venue_model');
    } 

    /*
     * Listing of venues
     */
    function index()
    {
        $data['venues'] = $this->Venue_model->get_all_venues();
        
        $data['_view'] = 'venue/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new venue
     */
    function add()
    {   
        $this->load->library('form_validation');

		$this->form_validation->set_rules('venueCode','VenueCode','required|max_length[10]');
		$this->form_validation->set_rules('venueName','VenueName','required|max_length[100]');
		$this->form_validation->set_rules('venueType','VenueType','required|max_length[50]');
		
		if($this->form_validation->run())     
        {   
            $params = array(
				'venueType' => $this->input->post('venueType'),
				'venueCode' => $this->input->post('venueCode'),
				'venueName' => $this->input->post('venueName'),
            );
            
            $venue_id = $this->Venue_model->add_venue($params);
            redirect('venue/index');
        }
        else
        {            
            $data['_view'] = 'venue/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a venue
     */
    function edit($venueID)
    {   
        // check if the venue exists before trying to edit it
        $data['venue'] = $this->Venue_model->get_venue($venueID);
        
        if(isset($data['venue']['venueID']))
        {
            $this->load->library('form_validation');

			$this->form_validation->set_rules('venueCode','VenueCode','required|max_length[10]');
			$this->form_validation->set_rules('venueName','VenueName','required|max_length[100]');
			$this->form_validation->set_rules('venueType','VenueType','required|max_length[50]');
		
			if($this->form_validation->run())     
            {   
                $params = array(
					'venueType' => $this->input->post('venueType'),
					'venueCode' => $this->input->post('venueCode'),
					'venueName' => $this->input->post('venueName'),
                );

                $this->Venue_model->update_venue($venueID,$params);            
                redirect('venue/index');
            }
            else
            {
                $data['_view'] = 'venue/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The venue you are trying to edit does not exist.');
    } 

    /*
     * Deleting venue
     */
    function remove($venueID)
    {
        $venue = $this->Venue_model->get_venue($venueID);

        // check if the venue exists before trying to delete it
        if(isset($venue['venueID']))
        {
            $this->Venue_model->delete_venue($venueID);
            redirect('venue/index');
        }
        else
            show_error('The venue you are trying to delete does not exist.');
    }
    
}
