<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Class_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get class by classID
     */
    function get_class($classID)
    {
        return $this->db->get_where('classes',array('classID'=>$classID))->row_array();
    }
        
    /*
     * Get all classes
     */
    function get_all_classes()
    {
        $this->db->order_by('classID', 'desc');
        return $this->db->get('classes')->result_array();
    }
        
    /*
     * function to add new class
     */
    function add_class($params)
    {
        $this->db->insert('classes',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update class
     */
    function update_class($classID,$params)
    {
        $this->db->where('classID',$classID);
        return $this->db->update('classes',$params);
    }
    
    /*
     * function to delete class
     */
    function delete_class($classID)
    {
        return $this->db->delete('classes',array('classID'=>$classID));
    }
}
