<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Venue_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get venue by venueID
     */
    function get_venue($venueID)
    {
        return $this->db->get_where('venues',array('venueID'=>$venueID))->row_array();
    }
        
    /*
     * Get all venues
     */
    function get_all_venues()
    {
        $this->db->order_by('venueID', 'desc');
        return $this->db->get('venues')->result_array();
    }
        
    /*
     * function to add new venue
     */
    function add_venue($params)
    {
        $this->db->insert('venues',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update venue
     */
    function update_venue($venueID,$params)
    {
        $this->db->where('venueID',$venueID);
        return $this->db->update('venues',$params);
    }
    
    /*
     * function to delete venue
     */
    function delete_venue($venueID)
    {
        return $this->db->delete('venues',array('venueID'=>$venueID));
    }
}
